In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv(r'D:\python\python1\house-price-ml\data\raw\new.csv',encoding='gbk',low_memory=False)
df.head(5)

,url,id,Lng,Lat,Cid,tradeTime,DOM,followers,totalPrice,price,...,buildingType,constructionTime,renovationCondition,buildingStructure,ladderRatio,elevator,fiveYearsProperty,subway,district,communityAverage
0,https://bj.lianjia.com/chengjiao/101084782030....,101084782030,116.475489,40.019520,1111027376244,2016-08-09,1464.0,106,415.0,31680,...,1.0,2005,3,6,0.217,1.0,0.0,1.0,7,56021.0
1,https://bj.lianjia.com/chengjiao/101086012217....,101086012217,116.453917,39.881534,1111027381879,2016-07-28,903.0,126,575.0,43436,...,1.0,2004,4,6,0.667,1.0,1.0,0.0,7,71539.0
2,https://bj.lianjia.com/chengjiao/101086041636....,101086041636,116.561978,39.877145,1111040862969,2016-12-11,1271.0,48,1030.0,52021,...,4.0,2005,3,6,0.500,1.0,0.0,0.0,7,48160.0
3,https://bj.lianjia.com/chengjiao/101086406841....,101086406841,116.438010,40.076114,1111043185817,2016-09-30,965.0,138,297.5,22202,...,1.0,2008,1,6,0.273,1.0,0.0,0.0,6,51238.0
4,https://bj.lianjia.com/chengjiao/101086920653....,101086920653,116.428392,39.886229,1111027381174,2016-08-28,927.0,286,392.0,48396,...,4.0,1960,2,2,0.333,0.0,1.0,1.0,1,62588.0

In [2]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 318851 entries, 0 to 318850
Data columns (total 26 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   url                  318851 non-null  str
 1   id                   318851 non-null  str
 2   Lng                  318851 non-null  float64
 3   Lat                  318851 non-null  float64
 4   Cid                  318851 non-null  int64
 5   tradeTime            318851 non-null  str
 6   DOM                  160874 non-null  float64
 7   followers            318851 non-null  int64
 8   totalPrice           318851 non-null  float64
 9   price                318851 non-null  int64
 10  square               318851 non-null  float64
 11  livingRoom           318851 non-null  str
 12  drawingRoom          318851 non-null  str
 13  kitchen              318851 non-null  int64
 14  bathRoom             318851 non-null  str
 15  floor                318851 non-null  str
 16  buildingType         316830 non-null  float64
 17  constructionTime     318851 non-null  str
 18  renovationCondition  318851 non-null  int64
 19  buildingStructure    318851 non-null  int64
 20  ladderRatio          318851 non-null  float64
 21  elevator             318819 non-null  float64
 22  fiveYearsProperty    318819 non-null  float64
 23  subway               318819 non-null  float64
 24  district             318851 non-null  int64
 25  communityAverage     318388 non-null  float64
dtypes: float64(11), int64(7), str(8)
memory usage: 63.2 MB
None

In [3]:
df.describe()

,Lng,Lat,Cid,DOM,followers,totalPrice,price,square,kitchen,buildingType,renovationCondition,buildingStructure,ladderRatio,elevator,fiveYearsProperty,subway,district,communityAverage
count,318851.000000,318851.000000,3.188510e+05,160874.000000,318851.000000,318851.000000,318851.000000,318851.000000,318851.000000,316830.000000,318851.000000,318851.000000,3.188510e+05,318819.000000,318819.000000,318819.000000,318851.000000,318388.000000
mean,116.418459,39.949591,1.129113e+12,28.822339,16.731508,349.030201,43530.436379,83.240597,0.994599,3.009790,2.606330,4.451026,6.316486e+01,0.577055,0.645601,0.601112,6.763564,63682.446305
std,0.112054,0.091983,2.363447e+12,50.237343,34.209185,230.780778,21709.024204,37.234661,0.109609,1.269857,1.311739,1.901753,2.506851e+04,0.494028,0.478331,0.489670,2.812616,22329.215447
min,116.072514,39.627030,1.111027e+12,1.000000,0.000000,0.100000,1.000000,6.900000,0.000000,0.048000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,1.000000,10847.000000
25%,116.344985,39.893200,1.111027e+12,1.000000,0.000000,205.000000,28050.000000,57.900000,1.000000,1.000000,1.000000,2.000000,2.500000e-01,0.000000,0.000000,0.000000,6.000000,46339.000000
50%,116.416780,39.934527,1.111027e+12,6.000000,5.000000,294.000000,38737.000000,74.260000,1.000000,4.000000,3.000000,6.000000,3.330000e-01,1.000000,1.000000,1.000000,7.000000,59015.000000
75%,116.477581,40.003018,1.111027e+12,37.000000,18.000000,425.500000,53819.500000,98.710000,1.000000,4.000000,4.000000,6.000000,5.000000e-01,1.000000,1.000000,1.000000,8.000000,75950.000000
max,116.732378,40.252758,1.114620e+15,1677.000000,1143.000000,18130.000000,156250.000000,1745.500000,4.000000,4.000000,4.000000,6.000000,1.000940e+07,1.000000,1.000000,1.000000,13.000000,183109.000000

In [4]:
df.shape

(318851, 26)

In [5]:
df.columns

Index(['url', 'id', 'Lng', 'Lat', 'Cid', 'tradeTime', 'DOM', 'followers',
       'totalPrice', 'price', 'square', 'livingRoom', 'drawingRoom', 'kitchen',
       'bathRoom', 'floor', 'buildingType', 'constructionTime',
       'renovationCondition', 'buildingStructure', 'ladderRatio', 'elevator',
       'fiveYearsProperty', 'subway', 'district', 'communityAverage'],
      dtype='str')

In [6]:
columns_del=['url','id','Cid','DOM','price']
df.drop(columns_del, axis=1, inplace=True, errors='ignore')
df.head()

,Lng,Lat,tradeTime,followers,totalPrice,square,livingRoom,drawingRoom,kitchen,bathRoom,...,buildingType,constructionTime,renovationCondition,buildingStructure,ladderRatio,elevator,fiveYearsProperty,subway,district,communityAverage
0,116.475489,40.019520,2016-08-09,106,415.0,131.00,2,1,1,1,...,1.0,2005,3,6,0.217,1.0,0.0,1.0,7,56021.0
1,116.453917,39.881534,2016-07-28,126,575.0,132.38,2,2,1,2,...,1.0,2004,4,6,0.667,1.0,1.0,0.0,7,71539.0
2,116.561978,39.877145,2016-12-11,48,1030.0,198.00,3,2,1,3,...,4.0,2005,3,6,0.500,1.0,0.0,0.0,7,48160.0
3,116.438010,40.076114,2016-09-30,138,297.5,134.00,3,1,1,1,...,1.0,2008,1,6,0.273,1.0,0.0,0.0,6,51238.0
4,116.428392,39.886229,2016-08-28,286,392.0,81.00,2,1,1,1,...,4.0,1960,2,2,0.333,0.0,1.0,1.0,1,62588.0

In [7]:
df.duplicated().sum()

np.int64(27)

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df.shape

(318824, 21)

In [10]:
df.index=range(df.shape[0])
df.index

RangeIndex(start=0, stop=318824, step=1)

In [11]:
df.isnull().sum()

Lng                       0
Lat                       0
tradeTime                 0
followers                 0
totalPrice                0
square                    0
livingRoom                0
drawingRoom               0
kitchen                   0
bathRoom                  0
floor                     0
buildingType           2021
constructionTime          0
renovationCondition       0
buildingStructure         0
ladderRatio               0
elevator                 31
fiveYearsProperty        31
subway                   31
district                  0
communityAverage        463
dtype: int64

In [12]:
missing=df.isnull().mean()
missing_del=missing[missing>0.25].index
df.drop(columns=missing_del, inplace=True)

In [13]:
df.shape

(318824, 21)

In [14]:
buildingType_mode=df['buildingType'].mode()[0]
df['buildingType']=df['buildingType'].fillna(buildingType_mode)
elevator_mode=df['elevator'].mode()[0]
df['elevator']=df['elevator'].fillna(elevator_mode)

In [15]:
df.isnull().sum()

Lng                      0
Lat                      0
tradeTime                0
followers                0
totalPrice               0
square                   0
livingRoom               0
drawingRoom              0
kitchen                  0
bathRoom                 0
floor                    0
buildingType             0
constructionTime         0
renovationCondition      0
buildingStructure        0
ladderRatio              0
elevator                 0
fiveYearsProperty       31
subway                  31
district                 0
communityAverage       463
dtype: int64

In [16]:
df['fiveYearsProperty']=df['fiveYearsProperty'].fillna(0)
df.isnull().sum()

Lng                      0
Lat                      0
tradeTime                0
followers                0
totalPrice               0
square                   0
livingRoom               0
drawingRoom              0
kitchen                  0
bathRoom                 0
floor                    0
buildingType             0
constructionTime         0
renovationCondition      0
buildingStructure        0
ladderRatio              0
elevator                 0
fiveYearsProperty        0
subway                  31
district                 0
communityAverage       463
dtype: int64

In [17]:
district_median=df.groupby('district')['communityAverage'].median()
missing_Average=df['communityAverage'].isnull()
df.loc[missing_Average, 'communityAverage']=df.loc[missing_Average, 'district'].map(district_median)
df.isnull().sum()

Lng                     0
Lat                     0
tradeTime               0
followers               0
totalPrice              0
square                  0
livingRoom              0
drawingRoom             0
kitchen                 0
bathRoom                0
floor                   0
buildingType            0
constructionTime        0
renovationCondition     0
buildingStructure       0
ladderRatio             0
elevator                0
fiveYearsProperty       0
subway                 31
district                0
communityAverage        0
dtype: int64

In [18]:
subway_mode=df['subway'].mode()[0]
df['subway']=df['subway'].fillna(subway_mode)
df.isnull().sum()

Lng                    0
Lat                    0
tradeTime              0
followers              0
totalPrice             0
square                 0
livingRoom             0
drawingRoom            0
kitchen                0
bathRoom               0
floor                  0
buildingType           0
constructionTime       0
renovationCondition    0
buildingStructure      0
ladderRatio            0
elevator               0
fiveYearsProperty      0
subway                 0
district               0
communityAverage       0
dtype: int64

In [19]:
df.describe()

,Lng,Lat,followers,totalPrice,square,kitchen,buildingType,renovationCondition,buildingStructure,ladderRatio,elevator,fiveYearsProperty,subway,district,communityAverage
count,318824.000000,318824.000000,318824.000000,318824.000000,318824.000000,318824.000000,318824.000000,318824.000000,318824.000000,3.188240e+05,318824.000000,318824.000000,318824.000000,318824.000000,318824.000000
mean,116.418467,39.949592,16.732915,349.052183,83.242745,0.994627,3.016067,2.606466,4.451095,6.317019e+01,0.577112,0.645582,0.601184,6.763713,63710.025409
std,0.112048,0.091980,34.210291,230.776230,37.234028,0.109314,1.268251,1.311708,1.901733,2.506957e+04,0.494019,0.478337,0.489655,2.812481,22336.156593
min,116.072514,39.627030,0.000000,0.100000,6.900000,0.000000,0.048000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,1.000000,10847.000000
25%,116.344985,39.893200,0.000000,205.000000,57.900000,1.000000,1.000000,1.000000,2.000000,2.500000e-01,0.000000,0.000000,0.000000,6.000000,46339.000000
50%,116.416780,39.934528,5.000000,294.000000,74.260000,1.000000,4.000000,3.000000,6.000000,3.330000e-01,1.000000,1.000000,1.000000,7.000000,59015.000000
75%,116.477581,40.003018,18.000000,425.500000,98.710000,1.000000,4.000000,4.000000,6.000000,5.000000e-01,1.000000,1.000000,1.000000,8.000000,75993.000000
max,116.732378,40.252758,1143.000000,18130.000000,1745.500000,4.000000,4.000000,4.000000,6.000000,1.000940e+07,1.000000,1.000000,1.000000,13.000000,183109.000000

In [20]:
float_cols=['Lng', 'Lat','totalPrice','square','communityAverage']
for col in float_cols:
    df[col]=pd.to_numeric(df[col], errors='coerce')
int_cols=['livingRoom','drawingRoom','kitchen','bathRoom','elevator','subway','fiveYearsProperty']
for cols in int_cols:
    df[cols]=pd.to_numeric(df[cols],errors='coerce').fillna(0).astype(int)

In [21]:
print(df.dtypes)

Lng                    float64
Lat                    float64
tradeTime                  str
followers                int64
totalPrice             float64
square                 float64
livingRoom               int64
drawingRoom              int64
kitchen                  int64
bathRoom                 int64
floor                      str
buildingType           float64
constructionTime           str
renovationCondition      int64
buildingStructure        int64
ladderRatio            float64
elevator                 int64
fiveYearsProperty        int64
subway                   int64
district                 int64
communityAverage       float64
dtype: object

In [22]:
df['constructionTime']=pd.to_numeric(df['constructionTime'],errors='coerce')

In [23]:
print(df.dtypes)

Lng                    float64
Lat                    float64
tradeTime                  str
followers                int64
totalPrice             float64
square                 float64
livingRoom               int64
drawingRoom              int64
kitchen                  int64
bathRoom                 int64
floor                      str
buildingType           float64
constructionTime       float64
renovationCondition      int64
buildingStructure        int64
ladderRatio            float64
elevator                 int64
fiveYearsProperty        int64
subway                   int64
district                 int64
communityAverage       float64
dtype: object

In [24]:
df.head(20)

,Lng,Lat,tradeTime,followers,totalPrice,square,livingRoom,drawingRoom,kitchen,bathRoom,...,buildingType,constructionTime,renovationCondition,buildingStructure,ladderRatio,elevator,fiveYearsProperty,subway,district,communityAverage
0,116.475489,40.019520,2016-08-09,106,415.0,131.00,2,1,1,1,...,1.0,2005.0,3,6,0.217,1,0,1,7,56021.0
1,116.453917,39.881534,2016-07-28,126,575.0,132.38,2,2,1,2,...,1.0,2004.0,4,6,0.667,1,1,0,7,71539.0
2,116.561978,39.877145,2016-12-11,48,1030.0,198.00,3,2,1,3,...,4.0,2005.0,3,6,0.500,1,0,0,7,48160.0
3,116.438010,40.076114,2016-09-30,138,297.5,134.00,3,1,1,1,...,1.0,2008.0,1,6,0.273,1,0,0,6,51238.0
4,116.428392,39.886229,2016-08-28,286,392.0,81.00,2,1,1,1,...,4.0,1960.0,2,2,0.333,0,1,1,1,62588.0
5,116.466280,39.991363,2016-07-22,57,275.6,53.00,1,0,1,1,...,4.0,2005.0,3,6,0.333,1,1,0,7,67738.0
6,116.482586,39.891991,2016-07-14,167,275.0,73.00,2,1,1,1,...,4.0,1997.0,4,2,0.500,0,0,0,7,50112.0
7,116.453917,39.881534,2016-09-07,138,800.0,161.55,3,2,1,2,...,1.0,2004.0,4,6,0.667,1,1,0,7,71539.0
8,116.555729,40.162058,2016-09-04,218,134.0,48.00,1,0,1,1,...,3.0,2009.0,1,2,0.333,0,0,0,13,44235.0
9,116.453086,39.898397,2016-09-05,134,380.0,68.00,1,0,0,0,...,1.0,2009.0,4,6,0.308,1,1,1,1,78590.0
10,116.529489,39.890906,2016-08-24,95,840.0,266.00,4,2,1,3,...,4.0,2006.0,3,6,0.200,0,0,0,7,57260.0
11,116.555729,40.162058,2016-08-03,74,126.0,48.00,1,1,1,1,...,3.0,2009.0,3,2,0.333,0,1,0,13,44235.0
12,116.476170,39.844869,2016-08-25,50,948.0,238.00,4,2,1,4,...,4.0,2004.0,4,6,0.091,0,1,0,7,46867.0
13,116.399018,39.978141,2016-08-17,65,896.0,97.70,3,1,1,1,...,4.0,1991.0,3,2,0.333,0,1,1,10,123002.0
14,116.296286,39.870107,2016-06-17,90,285.0,80.13,1,1,1,1,...,1.0,2001.0,4,6,0.222,1,0,1,2,53588.0
15,116.329220,39.892447,2016-09-20,76,360.0,59.40,2,1,1,1,...,1.0,1990.0,3,6,0.250,1,0,1,2,59395.0
16,116.405549,39.975629,2016-07-22,39,700.0,178.96,4,1,1,1,...,1.0,1997.0,3,6,0.333,1,1,1,7,53730.0
17,116.284755,39.934530,2016-09-17,6,212.0,64.28,1,0,1,1,...,1.0,2009.0,3,6,0.111,1,0,1,8,70141.0
18,116.603852,39.893276,2016-06-20,130,336.0,111.30,2,1,1,1,...,4.0,2008.0,4,6,0.167,1,1,0,7,48859.0
19,116.284755,39.934530,2016-08-23,41,174.6,52.00,1,0,1,1,...,1.0,2009.0,3,6,0.111,1,0,1,8,70141.0

In [25]:
df['floor_level'] =df['floor'].str[0].map({'底':0,'低':1,'中':2,'高':3,'顶':4})
df['floor_sum'] =pd.to_numeric(df['floor'].str[1:], errors='coerce')
df['floor_level'] =df['floor_level'].fillna(-1).astype(int)
df['floor_sum']=df['floor_sum'].fillna(-1).astype(int)

In [26]:
df.head(200)

,Lng,Lat,tradeTime,followers,totalPrice,square,livingRoom,drawingRoom,kitchen,bathRoom,...,renovationCondition,buildingStructure,ladderRatio,elevator,fiveYearsProperty,subway,district,communityAverage,floor_level,floor_sum
0,116.475489,40.019520,2016-08-09,106,415.0,131.00,2,1,1,1,...,3,6,0.217,1,0,1,7,56021.0,3,26
1,116.453917,39.881534,2016-07-28,126,575.0,132.38,2,2,1,2,...,4,6,0.667,1,1,0,7,71539.0,3,22
2,116.561978,39.877145,2016-12-11,48,1030.0,198.00,3,2,1,3,...,3,6,0.500,1,0,0,7,48160.0,2,4
3,116.438010,40.076114,2016-09-30,138,297.5,134.00,3,1,1,1,...,1,6,0.273,1,0,0,6,51238.0,0,21
4,116.428392,39.886229,2016-08-28,286,392.0,81.00,2,1,1,1,...,2,2,0.333,0,1,1,1,62588.0,2,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,116.448302,39.960966,2016-09-26,36,312.0,117.75,2,1,1,1,...,4,6,0.400,1,0,0,7,34966.0,3,25
196,116.384462,39.907534,2016-07-31,12,1220.0,162.72,3,2,1,2,...,4,6,0.500,1,1,1,10,70502.0,2,11
197,116.254035,40.205429,2016-07-29,5,170.0,69.00,1,1,1,1,...,1,6,0.500,1,0,0,6,42231.0,2,21
198,116.467922,39.993105,2016-07-21,88,387.0,84.10,3,1,1,1,...,3,6,0.200,1,1,1,7,59262.0,1,18
199,116.223565,39.763920,2016-08-29,104,261.0,78.83,2,1,1,1,...,2,6,0.500,1,0,1,5,39756.0,2,20

In [27]:
df.drop('floor',axis=1, inplace=True, errors='ignore')

In [28]:
df.head()

,Lng,Lat,tradeTime,followers,totalPrice,square,livingRoom,drawingRoom,kitchen,bathRoom,...,renovationCondition,buildingStructure,ladderRatio,elevator,fiveYearsProperty,subway,district,communityAverage,floor_level,floor_sum
0,116.475489,40.019520,2016-08-09,106,415.0,131.00,2,1,1,1,...,3,6,0.217,1,0,1,7,56021.0,3,26
1,116.453917,39.881534,2016-07-28,126,575.0,132.38,2,2,1,2,...,4,6,0.667,1,1,0,7,71539.0,3,22
2,116.561978,39.877145,2016-12-11,48,1030.0,198.00,3,2,1,3,...,3,6,0.500,1,0,0,7,48160.0,2,4
3,116.438010,40.076114,2016-09-30,138,297.5,134.00,3,1,1,1,...,1,6,0.273,1,0,0,6,51238.0,0,21
4,116.428392,39.886229,2016-08-28,286,392.0,81.00,2,1,1,1,...,2,2,0.333,0,1,1,1,62588.0,2,6

In [29]:
df['tradeTime']=pd.to_datetime(df['tradeTime'], errors='coerce')
df['trade_year']=df['tradeTime'].dt.year
df['trade_month']=df['tradeTime'].dt.month
df.drop('tradeTime',axis=1, inplace=True,errors='ignore')
df.head()

,Lng,Lat,followers,totalPrice,square,livingRoom,drawingRoom,kitchen,bathRoom,buildingType,...,ladderRatio,elevator,fiveYearsProperty,subway,district,communityAverage,floor_level,floor_sum,trade_year,trade_month
0,116.475489,40.019520,106,415.0,131.00,2,1,1,1,1.0,...,0.217,1,0,1,7,56021.0,3,26,2016,8
1,116.453917,39.881534,126,575.0,132.38,2,2,1,2,1.0,...,0.667,1,1,0,7,71539.0,3,22,2016,7
2,116.561978,39.877145,48,1030.0,198.00,3,2,1,3,4.0,...,0.500,1,0,0,7,48160.0,2,4,2016,12
3,116.438010,40.076114,138,297.5,134.00,3,1,1,1,1.0,...,0.273,1,0,0,6,51238.0,0,21,2016,9
4,116.428392,39.886229,286,392.0,81.00,2,1,1,1,4.0,...,0.333,0,1,1,1,62588.0,2,6,2016,8

In [30]:
# plt.figure(figsize=(8, 4))
# plt.boxplot(df['totalPrice'].dropna(),orientation='horizontal')
# plt.show()
# down= df['totalPrice'].quantile(0.25)
# up= df['totalPrice'].quantile(0.75)
# IQR = up-down
# lower= down -1.5 * IQR
# upper=up+1.5 *IQR
# df=df[(df['totalPrice']>lower)&(df['totalPrice']<upper)]

In [31]:
df= df[(df['totalPrice']>50)&(df['totalPrice']<3000)]

In [32]:
df.describe()

,Lng,Lat,followers,totalPrice,square,livingRoom,drawingRoom,kitchen,bathRoom,buildingType,...,ladderRatio,elevator,fiveYearsProperty,subway,district,communityAverage,floor_level,floor_sum,trade_year,trade_month
count,317511.000000,317511.000000,317511.000000,317511.000000,317511.000000,317511.000000,317511.000000,317511.000000,317511.000000,317511.000000,...,3.175110e+05,317511.000000,317511.000000,317511.000000,317511.000000,317511.000000,317511.000000,317511.000000,317511.000000,317511.000000
mean,116.418535,39.949276,16.788574,349.701945,83.188202,2.010075,1.172063,0.995071,1.332618,3.015060,...,6.342964e+01,0.577117,0.647004,0.601718,6.764745,63745.958726,2.079043,13.238489,2014.792420,6.604996
std,0.112118,0.091829,34.206364,222.948656,36.863195,0.776239,0.521419,0.105669,17.037434,1.268684,...,2.512135e+04,0.494018,0.477902,0.489545,2.814666,22320.350685,1.116791,7.859683,1.649859,3.480471
min,116.072514,39.627030,0.000000,50.100000,6.900000,0.000000,0.000000,0.000000,0.000000,0.125000,...,0.000000e+00,0.000000,0.000000,0.000000,1.000000,10847.000000,-1.000000,-1.000000,2002.000000,1.000000
25%,116.344985,39.892781,0.000000,205.000000,57.910000,1.000000,1.000000,1.000000,1.000000,1.000000,...,2.500000e-01,0.000000,0.000000,0.000000,6.000000,46352.000000,1.000000,6.000000,2013.000000,3.000000
50%,116.416780,39.934527,5.000000,295.000000,74.220000,2.000000,1.000000,1.000000,1.000000,4.000000,...,3.330000e-01,1.000000,1.000000,1.000000,7.000000,59023.000000,2.000000,11.000000,2015.000000,7.000000
75%,116.477730,40.002381,18.000000,426.800000,98.620000,2.000000,1.000000,1.000000,1.000000,4.000000,...,5.000000e-01,1.000000,1.000000,1.000000,8.000000,76001.000000,3.000000,19.000000,2016.000000,10.000000
max,116.732378,40.252758,1143.000000,2987.000000,922.700000,9.000000,5.000000,4.000000,2011.000000,4.000000,...,1.000940e+07,1.000000,1.000000,1.000000,13.000000,183109.000000,4.000000,63.000000,2018.000000,12.000000

In [33]:
df=df[(df['square'] >= 20)&(df['square'] <= 500)]

In [34]:
df.describe()

,Lng,Lat,followers,totalPrice,square,livingRoom,drawingRoom,kitchen,bathRoom,buildingType,...,ladderRatio,elevator,fiveYearsProperty,subway,district,communityAverage,floor_level,floor_sum,trade_year,trade_month
count,317225.000000,317225.000000,317225.000000,317225.000000,317225.00000,317225.000000,317225.000000,317225.000000,317225.000000,317225.000000,...,3.172250e+05,317225.000000,317225.000000,317225.000000,317225.000000,317225.000000,317225.000000,317225.000000,317225.000000,317225.000000
mean,116.418554,39.949281,16.791041,349.820516,83.22838,2.010794,1.172903,0.995612,1.333391,3.015168,...,6.348653e+01,0.577451,0.647310,0.601501,6.766302,63719.856840,2.080413,13.245403,2014.792378,6.605353
std,0.112158,0.091849,34.204356,222.766630,36.69388,0.775863,0.520612,0.103068,17.045070,1.268797,...,2.513267e+04,0.493966,0.477808,0.489590,2.812454,22305.215486,1.115860,7.855492,1.650046,3.480542
min,116.072514,39.627030,0.000000,50.100000,20.00000,0.000000,0.000000,0.000000,0.000000,0.125000,...,0.000000e+00,0.000000,0.000000,0.000000,1.000000,10847.000000,-1.000000,-1.000000,2002.000000,1.000000
25%,116.344985,39.892777,0.000000,205.000000,57.95000,1.000000,1.000000,1.000000,1.000000,1.000000,...,2.500000e-01,0.000000,0.000000,0.000000,6.000000,46352.000000,1.000000,6.000000,2013.000000,3.000000
50%,116.416780,39.934527,5.000000,295.000000,74.29000,2.000000,1.000000,1.000000,1.000000,4.000000,...,3.330000e-01,1.000000,1.000000,1.000000,7.000000,59023.000000,2.000000,11.000000,2015.000000,7.000000
75%,116.477730,40.002381,18.000000,427.000000,98.64000,2.000000,1.000000,1.000000,1.000000,4.000000,...,5.000000e-01,1.000000,1.000000,1.000000,8.000000,75993.000000,3.000000,19.000000,2016.000000,10.000000
max,116.732378,40.252758,1143.000000,2987.000000,497.65000,9.000000,5.000000,4.000000,2011.000000,4.000000,...,1.000940e+07,1.000000,1.000000,1.000000,13.000000,183109.000000,4.000000,63.000000,2018.000000,12.000000

In [35]:
df= df[(df['livingRoom']!=0)&(df['drawingRoom']!=0)&(df['kitchen']!=0)&(df['bathRoom']!=0)]
df.describe()

,Lng,Lat,followers,totalPrice,square,livingRoom,drawingRoom,kitchen,bathRoom,buildingType,...,ladderRatio,elevator,fiveYearsProperty,subway,district,communityAverage,floor_level,floor_sum,trade_year,trade_month
count,296672.000000,296672.000000,296672.000000,296672.000000,296672.000000,296672.000000,296672.000000,296672.000000,296672.000000,296672.000000,...,2.966720e+05,296672.000000,296672.000000,296672.000000,296672.000000,296672.000000,296672.000000,296672.000000,296672.000000,296672.000000
mean,116.418953,39.949559,16.809358,358.459876,85.412237,2.065628,1.249043,1.002757,1.202483,3.050736,...,6.786713e+01,0.559706,0.659031,0.597424,6.750317,63658.691693,2.083810,13.010240,2014.784108,6.603589
std,0.111501,0.092292,34.047679,225.243270,36.534183,0.758466,0.440743,0.053895,0.442148,1.259475,...,2.598867e+04,0.496423,0.474036,0.490418,2.794766,22347.259543,1.122889,7.831293,1.649120,3.480383
min,116.072514,39.627030,0.000000,50.100000,20.210000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.400000e-02,0.000000,0.000000,0.000000,1.000000,10847.000000,-1.000000,-1.000000,2002.000000,1.000000
25%,116.345810,39.892604,0.000000,212.000000,59.640000,2.000000,1.000000,1.000000,1.000000,1.000000,...,2.500000e-01,0.000000,0.000000,0.000000,6.000000,46339.000000,1.000000,6.000000,2013.000000,3.000000
50%,116.416780,39.935087,5.000000,300.000000,77.050000,2.000000,1.000000,1.000000,1.000000,4.000000,...,3.330000e-01,1.000000,1.000000,1.000000,7.000000,59015.000000,2.000000,11.000000,2015.000000,7.000000
75%,116.477171,40.003028,18.000000,435.000000,100.500000,3.000000,1.000000,1.000000,1.000000,4.000000,...,5.000000e-01,1.000000,1.000000,1.000000,8.000000,75858.000000,3.000000,19.000000,2016.000000,10.000000
max,116.732378,40.252758,1143.000000,2987.000000,497.650000,9.000000,5.000000,4.000000,7.000000,4.000000,...,1.000940e+07,1.000000,1.000000,1.000000,13.000000,183109.000000,4.000000,63.000000,2018.000000,12.000000